const $=s=>document.querySelector(s),V=$('#view'),fm=n=>n.toLocaleString('ru-RU')+' ₸';
const P={home:'<path d="M3 11l9-8 9 8v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/>',menu:'<path d="M5 8h12v6a5 5 0 0 1-5 5h-2a5 5 0 0 1-5-5zM17 9h2a2 2 0 0 1 0 5h-2M8 2v3M12 2v3"/>',cart:'<path d="M3 4h2l2.4 11h10.2L20 7H6.5"/><circle cx="9" cy="19.5" r="1.4"/><circle cx="17" cy="19.5" r="1.4"/>',places:'<path d="M12 21s7-6 7-12a7 7 0 0 0-14 0c0 6 7 12 7 12z"/><circle cx="12" cy="9" r="2.5"/>',profile:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',phone:'<path d="M5 4h4l2 5-2.5 1.5a11 11 0 0 0 5 5L15 13l5 2v4a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2z"/>',back:'<path d="M15 5l-7 7 7 7"/>',chev:'<path d="M9 5l7 7-7 7"/>',search:'<circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"/>',plus:'<path d="M12 5v14M5 12h14"/>',map:'<path d="M9 4L3 6v14l6-2 6 2 6-2V4l-6 2zM9 4v14M15 6v14"/>',star:'<path d="M12 2.5l2.9 6.1 6.6.8-4.9 4.6 1.3 6.6L12 17.3 6.1 20.6l1.3-6.6L2.5 9.4l6.6-.8z"/>',lock:'<rect x="5" y="11" width="14" height="9" rx="2"/><path d="M8 11V8a4 4 0 0 1 8 0v3"/>',qr:'<path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h2v2h-2zM18 14h2v6h-4M14 18h2"/>',ext:'<path d="M7 17L17 7M8 7h9v9"/>',refresh:'<path d="M20 12a8 8 0 1 1-2.6-5.9"/><path d="M20 4v5h-5"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',grid:'<rect x="4" y="4" width="7" height="7" rx="2"/><rect x="13" y="4" width="7" height="7" rx="2"/><rect x="4" y="13" width="7" height="7" rx="2"/><rect x="13" y="13" width="7" height="7" rx="2"/>',ice:'<path d="M7 7h10l-1.2 12a2 2 0 0 1-2 1.8h-3.6a2 2 0 0 1-2-1.8z"/><path d="M12 3l1 4M9 11h6"/>',spark:'<path d="M12 3l1.8 5.2L19 10l-5.2 1.8L12 17l-1.8-5.2L5 10l5.2-1.8z"/><path d="M19 17v4M17 19h4"/>',leaf:'<path d="M5 19C5 9 11 4 20 4c0 9-5 15-15 15zM5 19l8-8"/>',cake:'<path d="M4 20h16v-6H4zM6 14v-3h12v3M12 11V7"/>',croi:'<path d="M4 15c1-5 5-8 8-8s7 3 8 8l-3 1-2-3-3 1-3-1-2 3z"/>',kids:'<circle cx="12" cy="12" r="8"/><path d="M9 10h.01M15 10h.01M8.5 14c1 1.8 5.9 1.8 7 0"/>',gift:'<rect x="3" y="8" width="18" height="5" rx="1"/><path d="M5 13v8h14v-8M12 8v13M12 8C9 8 8 4 10 4s2 4 2 4 0-4 2-4 1 4-2 4"/>',insta:'<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><path d="M17.5 6.5h.01"/>'};
const ic=(n,c='')=>`<svg class="i ${c}" viewBox="0 0 24 24">${P[n]}</svg>`;
const CI={all:'grid',hot:'menu',ice:'ice',cold:'spark',tea:'leaf',dess:'cake',bake:'croi',kids:'kids'};
const lgo=(c='')=>`<svg class="lg ${c}"><use href="#lgo" width="100%" height="100%"/></svg>`;
(function(){const s=$('#lgo');s.setAttribute('viewBox',LOGO.vb.join(' '));s.innerHTML=`<path d="${LOGO.d}"/>`})();
const DEF=()=>({cups:1,total:1,gifts:0,hist:[{t:Date.now()-172800000,x:'Напиток №1 зачтён'}],id:'N5-'+Math.floor(1000+Math.random()*9000)});let S=DEF(),C=[];
try{S=Object.assign(S,JSON.parse(localStorage.getItem('k5v5')||'{}'));C=JSON.parse(localStorage.getItem('k5c')||'[]')}catch(e){}
if(S.cups>=6)S.cups=0;
const save=()=>{try{localStorage.setItem('k5v5',JSON.stringify(S));localStorage.setItem('k5c',JSON.stringify(C))}catch(e){}};
let uid=0,mcat='all',qt=null,hist=[],cur='',tt=null,q0='';
const find=id=>ALL.find(a=>a.id===id),line=l=>{const x=find(l.id);return x.s[l.z][1]+(l.y>=0?250:0)+(l.m?690:0)},cnt=()=>C.reduce((a,l)=>a+l.q,0),sum=()=>C.reduce((a,l)=>a+line(l)*l.q,0);
function fly(el){const nb=$('nav .cb');if(!el||!nb)return;const a=el.getBoundingClientRect(),b=nb.getBoundingClientRect(),d=document.createElement('div');d.className='fly';d.style.left=a.left+a.width/2-8+'px';d.style.top=a.top+a.height/2-8+'px';document.body.appendChild(d);d.animate([{transform:'translate(0,0) scale(1)',opacity:1},{transform:`translate(${b.left+b.width/2-a.left-a.width/2}px,${b.top+b.height/2-a.top-a.height/2}px) scale(.3)`,opacity:.4}],{duration:700,easing:'cubic-bezier(.5,-.3,.7,1)'}).onfinish=()=>d.remove()}
function addCart(id,z=0,y=-1,m=0,el){const l=C.find(l=>l.id===id&&l.z===z&&l.y===y&&l.m===m);l?l.q++:C.push({id,z,y,m,q:1});save();fly(el);setTimeout(()=>badge(true),600);toast('Добавлено: '+find(id).n)}
function badge(p){const b=$('#bdg');if(!b)return;b.textContent=cnt();b.style.display=cnt()?'':'none';if(p){b.classList.remove('pop');void b.offsetWidth;b.classList.add('pop')}}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('on');clearTimeout(tt);tt=setTimeout(()=>e.classList.remove('on'),1800)}
/* cup & qr */
function cup(st='on',an,six){const i=++uid,on=st==='on'||st==='gift',gold=st==='gift'||st==='ready',D='M14 30h72l-8 90a6 6 0 0 1-6 5H28a6 6 0 0 1-6-5z',a=an!=null,sk=on?(gold?'#ffd27d':'#bdfbe3'):(gold?'#e4b055':'#7d8b85'),W='M0 6Q12.5 0 25 6T50 6T75 6T100 6T125 6T150 6T175 6T200 6V130H0Z',c1=gold?'#c96a12':'#9a5718',c2=gold?'#ffd27d':'#f0b45b';return`<svg class="cp ${st}" viewBox="0 0 100 128"><defs><clipPath id="cc${i}"><path d="${D}"/></clipPath><linearGradient id="cl${i}" x1="0" y1="1" x2="0" y2="0"><stop offset="0" stop-color="${c1}"/><stop offset="1" stop-color="${c2}"/></linearGradient></defs><path d="${D}" fill="#0c1814"/><g clip-path="url(#cc${i})"><g class="liq" style="transform:translateY(${on&&!a?42:134}px);transition:transform 3.4s cubic-bezier(.25,.7,.3,1)"><g><path d="${W}" fill="#f6e7c6" style="animation:wv 1.7s linear infinite"/></g><g transform="translate(0 7)"><path d="${W}" fill="url(#cl${i})" style="animation:wv 2.3s linear infinite reverse"/></g><circle cx="22" cy="3.5" r="1.7" fill="#fff" opacity=".7"/><circle cx="48" cy="2.5" r="1.3" fill="#fff" opacity=".6"/><circle cx="71" cy="4" r="1.9" fill="#fff" opacity=".7"/><circle cx="35" cy="5" r="1.2" fill="#fff" opacity=".5"/></g></g><path d="${D}" fill="none" stroke="${sk}" stroke-width="3.2" stroke-linejoin="round"/><rect x="9" y="17" width="82" height="15" rx="6" fill="${on?'#0b2a20':'#121d18'}" stroke="${sk}" stroke-width="2.6"/>${a?'<rect class="stm" x="48.5" y="-18" width="3" height="78" rx="1.5" fill="#c98a46" style="opacity:0;transform-origin:50% 0;transform:scaleY(0)"/>':''}<circle class="ck" cx="50" cy="84" r="19" fill="${on?'#fff':'none'}" stroke="${on?'none':sk}" stroke-width="2" ${on?'':'stroke-dasharray="4 4"'} style="transform-origin:50px 84px;transform:scale(${on&&a?0:1});transition:transform .5s 3.2s cubic-bezier(.34,1.8,.64,1)"/>${on?`<path class="ck" d="M40 84l7 7 14-15" fill="none" stroke="${gold?'#b9701a':'#0a7a52'}" stroke-width="5.5" stroke-linecap="round" stroke-linejoin="round" style="transform-origin:50px 84px;transform:scale(${a?0:1});transition:transform .5s 3.2s cubic-bezier(.34,1.8,.64,1)"/>`:six?`<text x="50" y="92" text-anchor="middle" font-family="Montserrat,sans-serif" font-weight="800" font-size="22" fill="${sk}">+1</text>`:''}</svg>`}
function qr(tok,an){let s=0;for(const c of tok)s=(s*31+c.charCodeAt(0))>>>0;const r=()=>(s=(s*1664525+1013904223)>>>0)/4294967296,N=29,dl=y=>an?` class="m" style="animation-delay:${(y/N*1.25+Math.random()*.4).toFixed(2)}s"`:'';let o='';const fin=(x,y)=>{o+=`<g${dl(y)}><rect x="${x}" y="${y}" width="7" height="7" rx="1.8" fill="#0b2a20"/><rect x="${x+1}" y="${y+1}" width="5" height="5" rx="1.2" fill="#fff"/><rect x="${x+2}" y="${y+2}" width="3" height="3" rx="1" fill="#0b2a20"/></g>`};for(let y=0;y<N;y++)for(let x=0;x<N;x++){if((x<8&&y<8)||(x>20&&y<8)||(x<8&&y>20)||(Math.abs(x-14)<5.6&&Math.abs(y-14)<5.6))continue;if(r()>.5)o+=`<rect${dl(y)} x="${x+.08}" y="${y+.08}" width=".84" height=".84" rx=".3" fill="#0b2a20"/>`}fin(0,0);fin(22,0);fin(0,22);return`<svg viewBox="0 0 29 29">${o}<g${an?' class="m" style="animation-delay:.75s"':''}><circle cx="14.5" cy="14.5" r="4.9" fill="#07130e" stroke="#e4b055" stroke-width=".25"/><use href="#lgo" x="10.7" y="10.7" width="7.6" height="7.6" fill="#f7d99a" fill-rule="evenodd"/></g></svg>`}
const pr=x=>(x.s.length>1?'от ':'')+fm(x.s[0][1]),tg=x=>x.tag?`<span class="tag ${x.tag}">${x.tag==='hit'?'HIT':'NEW'}</span>`:'';
const sec=(s,t,a='')=>`<div class="sh rv"><div><small>${s}</small><h2>${t}</h2></div>${a}</div>`;
const feed=h=>`<div class="fd rv"><button class="fa l" data-d="-1" aria-label="Назад">${ic('back')}</button><div class="feed">${h}</div><button class="fa r" data-d="1" aria-label="Вперёд">${ic('chev')}</button></div>`;
function status(l){const n=new Date(),h=n.getHours()+n.getMinutes()/60,d=n.getDay(),c=(l.c2&&(d===5||d===6||d===0))?l.c2:l.c,p=v=>String(v%24).padStart(2,'0')+':00';return h>=l.o&&h<c?`<span class="st o">Открыто до ${p(c)}</span>`:`<span class="st c">Закрыто · с ${p(l.o)}</span>`}
function locCard(l){return`<div class="lc2 rv"><img src="assets/${l.img}.jpg" alt="${l.n}" loading="lazy"><div class="li"><h3>${l.n}</h3>${l.a?`<div class="ad">${l.a}</div>`:''}<div class="hr">${ic('clock')}<span>${l.h}</span></div></div><a class="g2" target="_blank" rel="noopener" href="${l.g}" aria-label="Открыть в 2GIS">2GIS</a></div>`}
/* pages */
function home(){const nw=ALL.filter(x=>x.tag==='new'),m=LOCS[0];return`<div class="pg"><div class="hero"><video src="assets/video.mp4" poster="assets/video.jpg" autoplay muted loop playsinline></video><div class="hc"><h1>Не просто<br><em>кофе</em></h1><p>Авторские напитки, свежая выпечка и десерты. Каждый 6-й напиток — в подарок.</p><div class="bt"><a class="btn" href="#/menu">Смотреть меню</a><a class="btn gl" href="#/places">Адреса</a></div></div></div>
<a class="card loy rv" href="#/loyalty">${cup(S.cups>0?'on':'off')}<div style="flex:1"><h3>Карта гостя 5+1</h3><p>${S.cups<5?'До бесплатного напитка: '+(5-S.cups):'Следующий напиток — бесплатно'}</p><div class="bar"><i style="width:${S.cups/5*100}%"></i></div></div></a>
${sec('Предложения','Акции')}${feed(PROMOS.map(p=>`<button class="pm" data-p="${p.id}" style="--c:${p.col}"><img src="assets/${p.img}.jpg" alt="${p.t}"><i class="sn"></i><span class="ch">${p.c}</span><div><b>${p.t}</b><small>${p.s}</small></div></button>`).join(''))}
${sec('Выбирайте','Категории')}<div class="bento rv">${BENTO.map((b,i)=>`<a class="bn bt${i+1}" href="#/menu/${b[0]}"><img src="assets/${b[2]}.jpg" alt=""><span>${b[1]}</span>${ic('chev')}</a>`).join('')}</div>
${sec('Только что в меню','Новинки','<a href="#/menu">Всё меню</a>')}${feed(nw.map(x=>`<div class="nw" data-h="#/product/${x.id}"><div class="im"><img src="assets/${x.img}.jpg" alt="${x.n}">${tg(x)}<button class="add" data-a="${x.id}" aria-label="Добавить">${ic('plus')}</button></div><b>${x.n}</b><small>${pr(x)}</small></div>`).join(''))}
${sec('Заходите','Адреса')}${locCard(m)}<a class="btn gl rv" href="#/places" style="margin-top:4px">${ic('places')}Все адреса и режим работы</a>${sec('Живая атмосфера','Атмосфера')}${feed(`<div class="nw" style="width:190px"><div class="im" style="height:250px"><video src="assets/v2.mp4" poster="assets/v2.jpg" autoplay muted loop playsinline style="width:100%;height:100%;object-fit:cover"></video></div></div><div class="nw" style="width:190px"><div class="im" style="height:250px"><video src="assets/v3.mp4" poster="assets/v3.jpg" autoplay muted loop playsinline style="width:100%;height:100%;object-fit:cover"></video></div></div>`+ATM.map(c=>`<div class="nw" style="width:190px"><div class="im" style="height:250px"><img loading="lazy" src="assets/${c}.jpg" alt=""></div></div>`).join(''))}</div>`}
function mlist(){const q=q0.trim().toLowerCase(),L=(mcat==='all'?CATS:CATS.filter(c=>c.id===mcat)).map(c=>({...c,items:c.items.filter(x=>!q||x.n.toLowerCase().includes(q))})).filter(c=>c.items.length);return L.length?L.map(c=>`${sec(c.items.length+' поз.',c.n)}<div class="grid">${c.items.map(x=>`<div class="mc rv" data-h="#/product/${x.id}"><div class="im"><img loading="lazy" src="assets/${x.img}.jpg" alt="${x.n}">${tg(x)}<span class="pr">${pr(x)}</span><button class="add" data-a="${x.id}" title="+ Добавить" aria-label="Добавить">${ic('plus')}</button></div><div class="bd"><b>${x.n}</b><small>${x.s.map(s=>s[0]).join(' · ')}</small></div></div>`).join('')}</div>`).join(''):'<p class="no">Ничего не найдено</p>'}
function menu(){return`<div class="pg">${sec('Всё для вас','Меню')}<div class="srch">${ic('search')}<input id="qs" type="search" placeholder="Поиск по меню" value="${q0}"></div><div class="rbw"><div class="rib">${[{id:'all',n:'Всё'},...CATS].map(c=>`<button class="chip ${c.id===mcat?'on':''}" data-c="${c.id}">${ic(CI[c.id])}<span>${c.n}</span></button>`).join('')}</div></div><div id="ml">${mlist()}</div><p class="cap" style="margin-top:22px">Если у вас есть аллергия — предупредите кассира.</p></div>`}
function product(id){const x=find(id);if(!x)return'<div class="pg"><p class="no">Позиция не найдена</p></div>';return`<div class="pg pd"><div class="big"><img src="assets/${x.img}.jpg" alt="${x.n}"></div><div class="sheet"><h1>${x.n}</h1><p>${x.d||x.cn}</p><div class="lab">${x.s.length>1?'Объём':'Порция'}</div><div class="opt" id="sz">${x.s.map((s,i)=>`<button class="pill ${i?'':'on'}" data-i="${i}">${s[0]} · ${fm(s[1])}</button>`).join('')}</div>
${x.drink?`<div class="lab">Сироп +250 ₸</div><div class="opt" id="sy"><button class="pill on" data-i="-1">Без сиропа</button>${SYR.map((s,i)=>`<button class="pill" data-i="${i}">${s}</button>`).join('')}</div><div class="lab">Молоко</div><div class="opt" id="ml2"><button class="pill on" data-i="0">Обычное</button><button class="pill" data-i="1">Альтернативное +690 ₸</button></div>`:''}
<div class="sb"><div class="tt"><small>Итого</small><b id="tt"></b></div><button class="btn" id="addp">${ic('cart')}В корзину</button></div></div></div>`}
function bindProduct(id){const x=find(id);if(!x)return;let z=0,y=-1,m=0;const up=()=>$('#tt').textContent=fm(x.s[z][1]+(y>=0?250:0)+(m?690:0));const pick=(q,f)=>{const e=$(q);e&&e.addEventListener('click',ev=>{const b=ev.target.closest('.pill');if(!b)return;e.querySelectorAll('.pill').forEach(p=>p.classList.remove('on'));b.classList.add('on');f(+b.dataset.i);up()})};pick('#sz',i=>z=i);pick('#sy',i=>y=i);pick('#ml2',i=>m=i);up();$('#addp').onclick=e=>addCart(id,z,y,m,e.currentTarget)}
function cart(){if(!C.length)return`<div class="pg">${sec('Ваш заказ','Корзина')}<div class="empty">${ic('cart')}<h3>Корзина пуста</h3><p style="margin-bottom:22px">Добавьте напитки и выпечку из меню</p><a class="btn" href="#/menu">Перейти в меню</a></div></div>`;
return`<div class="pg">${sec('Ваш заказ','Корзина')}<div class="card pcard rv">${C.map((l,i)=>{const x=find(l.id);return`<div class="ci"><img src="assets/${x.img}.jpg" alt=""><div><b>${x.n}</b><small>${x.s[l.z][0]}${l.y>=0?' · '+SYR[l.y]:''}${l.m?' · альт. молоко':''}</small><div class="q"><button data-q="${i}" data-d="-1" aria-label="Меньше">−</button><span>${l.q}</span><button data-q="${i}" data-d="1" aria-label="Больше">+</button></div></div><em>${fm(line(l)*l.q)}</em></div>`}).join('')}</div>
<div class="card pcard rv" style="margin-top:14px"><div class="row"><span>Позиций</span><b>${cnt()}</b></div><div class="tot"><span>Итого</span><b>${fm(sum())}</b></div></div><button class="btn rv" id="pay" style="margin-top:16px">${ic('lock')}Оформить и оплатить</button><button class="btn gl rv" id="clr" style="margin-top:10px">Очистить корзину</button></div>`}
function places(){const ph=['t1','in1','wall','in2','t3','note','t4','latte','choc','tea','honey','berry','brulee','croissant'];return`<div class="pg"><div class="sh" style="margin-top:4px"><div><small>Павлодар · ${LOCS.length} точек</small><h2>Найти кофейню</h2></div></div>
<a class="card pcard gisb rv" target="_blank" rel="noopener" href="${G('Кофейня N5 Павлодар')}"><span class="gi">${ic('map')}</span><div><b>Все точки на карте</b><small>Открыть в 2GIS</small></div>${ic('ext')}</a>
${sec('Режим работы','Наши точки')}${LOCS.map(locCard).join('')}
${sec('Фирменная упаковка','Стаканчики и пакеты')}${feed(CUPS.map(c=>`<div class="nw" style="width:200px"><div class="im" style="height:260px"><img src="assets/${c}.jpg" alt=""></div></div>`).join(''))}
${sec('Живая атмосфера','Видео')}<div class="vid rv">${[1,2,3,4].map(i=>`<div class="v"><video src="assets/v${i}.mp4" poster="assets/v${i}.jpg" autoplay muted loop playsinline></video></div>`).join('')}</div>
${sec('Интерьер и подача','Фотогалерея')}<div class="phg">${ph.map(p=>`<img class="rv" loading="lazy" src="assets/${p}.jpg" alt="">`).join('')}</div>
${sec('Мы в сети','Контакты')}<div class="card rv"><div class="row"><span>Instagram</span><b><a target="_blank" rel="noopener" href="https://instagram.com/pekarnya_n5">@pekarnya_n5</a></b></div><div class="row"><span>Бронь столов</span><b>свободная рассадка</b></div><div class="row"><span>С питомцами</span><b>можно, кроме семейного зала</b></div></div></div>`}
function places(){return`<div class="pg">${sec('Режим работы','Адреса')}${LOCS.map(locCard).join('')}</div>`}
function loyalty(){return`<div class="pg">${sec('Купи 5 — 6-й в подарок','Карта 5+1','<div class="cnt" id="cnt"></div>')}
<div class="card pcard rv"><div class="cups" id="cups"></div><p class="lcap" id="lcap"></p><button class="btn rwd" id="oc" hidden>Бесплатный напиток доступен — показать купон</button></div>
<div class="card pcard rv" style="margin-top:14px"><div class="qlogo">${lgo()}</div><div id="qw"></div><div class="qa"><button class="btn" id="sc">${ic('qr')}[Демо] Сканировать у бариста</button><button class="btn gl" id="rq">${ic('refresh')}Обновить QR</button></div></div>
<div class="card pcard rv" style="margin-top:14px"><div class="row"><span>Регистрация карты</span><b>бесплатно, на кассе</b></div><div class="row"><span>Бонусы</span><b>10% с выпечки и десертов</b></div><div class="row"><span>Накопления</span><b>не сгорают</b></div></div></div>`}
function updCnt(){const n=Math.min(S.cups,5);$('#cnt').innerHTML=`<b>${n}</b><span>/5</span>`;$('#lcap').innerHTML=S.cups>=5?'Следующий напиток — <b>бесплатно!</b>':`До бесплатного напитка осталось: <b>${5-S.cups}</b>`;$('#oc').hidden=S.cups!==5}
function fillCup(c){c.querySelector('.liq').style.transform='translateY(42px)';c.querySelectorAll('.ck').forEach(k=>k.style.transform='scale(1)');const m=c.querySelector('.stm');m&&m.animate([{opacity:0,transform:'scaleY(0)'},{opacity:1,transform:'scaleY(1)',offset:.1},{opacity:1,transform:'scaleY(1)',offset:.85},{opacity:0,transform:'scaleY(1)'}],{duration:3300,fill:'forwards'})}
function cups(an){if(!$('#cups'))return;$('#cups').innerHTML=[0,1,2,3,4,5].map(i=>{const st=i<5?(i<S.cups?'on':'off'):(S.cups>=6?'gift':S.cups===5?'ready':'off'),on=st==='on'||st==='gift';return`<div>${cup(st,i===an?1:null,i===5)}<small class="${on?'on':''}">${i===5?'Бесплатный':i+1+'-й'}</small></div>`}).join('');updCnt();if(an!=null)setTimeout(()=>{const c=document.querySelectorAll('#cups .cp')[an];if(!c)return;fillCup(c);c.animate([{transform:'scale(1)'},{transform:'scale(1.12)'},{transform:'scale(1)'}],{duration:3600,easing:'ease-in-out'})},80)}
function lockB(v){const a=$('#sc'),b=$('#rq');if(a)a.disabled=v;if(b)b.disabled=v}
function qrAnim(cap,cb){clearTimeout(qt);const w=$('#qw');if(!w)return;lockB(true);w.innerHTML=`<div class="qr gen" id="qb"><span>${qr(S.id+Date.now(),1)}</span><div class="laser"></div></div><p class="cap" id="qcap">${cap}</p>`;qt=setTimeout(()=>{const c=$('#qcap');if(!c)return;c.textContent='Покажите код бариста · карта '+S.id;lockB(false);cb&&cb()},2100)}
function showReward(){celebrate();popup(`<div class="rglow"></div><div class="rcup">${cup('gift',1)}</div><h3>Вам доступен бесплатный напиток!</h3><p>Оплачивать не нужно — просто покажите этот экран или QR-код бариста на кассе!</p><div class="cw"><div class="coupon"><div class="ct">${lgo()}<span>КУПОН · КАРТА ${S.id}</span></div><div class="c100">100% СКИДКА</div><div class="c0">0 ₸</div><i class="cs"></i></div></div><button class="btn big" id="claim">Забрать бесплатный кофе</button>`,1,'rw');setTimeout(()=>{const c=document.querySelector('.rcup .cp');c&&fillCup(c)},350);$('#claim').onclick=()=>{closePop();celebrate();S.cups=6;S.gifts++;S.hist.unshift({t:Date.now(),x:'Бесплатный напиток получен'});save();cups(5);lockB(true);setTimeout(()=>{S.cups=0;save();cups();lockB(false)},4000)}}
function bindLoyalty(){cups();qrAnim('Генерация защищённого кода…');$('#rq').onclick=()=>qrAnim('Генерация защищённого кода…');$('#oc').onclick=showReward;$('#sc').onclick=()=>{if(!$('#qb'))return;qrAnim('Сканирование…',()=>{const q=$('#qb');q.classList.add('ok');beep(880,.15);setTimeout(()=>beep(1320,.25),130);navigator.vibrate&&navigator.vibrate([60,40,150]);if(S.cups>=5){setTimeout(showReward,700);return}S.cups++;S.total++;const n=S.cups;S.hist.unshift({t:Date.now(),x:'Напиток №'+n+' зачтён'});save();cups(n-1);lockB(true);setTimeout(()=>{lockB(false);q.classList.remove('ok')},3600);if(n>=5)setTimeout(showReward,3900)})}}
function profile(){const t=S.total,w=Math.min(100,S.cups/5*100);return`<div class="pg prof">${sec('Личный кабинет','Профиль')}
<div class="gcard pin" style="--d:.05s"><div class="wm">${lgo()}</div><div class="gh"><div class="glg">${lgo()}<span>Кофейня N5</span></div><em>КАРТА ГОСТЯ</em></div><div class="gb"><div class="av"><img id="avi" src="assets/4.jpg" alt="Полина"></div><div><h3>Полина</h3><div class="bad">Постоянный гость</div></div></div><div class="gf"><div><small>Номер карты</small><b>${S.id}</b></div><div class="gp"><small>${5-S.cups} до бесплатного напитка</small><div class="bar"><i style="width:${w}%"></i></div></div></div></div>
<div class="tiles"><div class="tile gb2 pin" style="--d:.2s"><span class="ti">${ic('menu')}</span><b data-n="${t}">0</b><small>напиток</small></div><div class="tile gb2 pin" style="--d:.3s"><span class="ti">${ic('gift')}</span><b data-n="${S.gifts}">0</b><small>бесплатных напитков</small></div><div class="tile gb2 pin" style="--d:.4s"><span class="ti">${ic('qr')}</span><b data-n="${5-S.cups}">0</b><small>до бесплатного напитка</small></div></div>
<a class="gb2 lk pin" style="--d:.5s" href="#/loyalty">${ic('qr')}<div><b>Карта лояльности 5+1</b><small>QR-код и стаканчики</small></div>${ic('chev')}</a>
<a class="gb2 lk pin" style="--d:.58s" href="#/places">${ic('places')}<div><b>Адреса и режим работы</b><small>${LOCS.length} точек</small></div>${ic('chev')}</a>
${sec('Последние начисления','История')}<div class="gb2 hst pin" style="--d:.66s">${S.hist.length?S.hist.slice(0,12).map(h=>`<div class="row"><span>${new Date(h.t).toLocaleString('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</span><b>${h.x}</b></div>`).join(''):'<p class="cap" style="margin:0">Пока пусто</p>'}</div>
<button class="btn gl pin" id="rs" style="margin-top:16px;--d:.74s">Сбросить демо-данные</button></div>`}
function bindProfile(){const im=$('#avi'),fb=()=>{im.replaceWith(Object.assign(document.createElement('div'),{innerHTML:lgo()}).firstChild)};im.onerror=fb;if(im.complete&&!im.naturalWidth)fb();$('#rs').onclick=()=>{S=DEF();save();route()};document.querySelectorAll('.tile b').forEach((e,i)=>{const n=+e.dataset.n,t0=performance.now()+300+i*100;(function f(x){const k=Math.min(1,Math.max(0,(x-t0)/900));e.textContent=Math.round(n*(1-Math.pow(1-k,3)));if(k<1)requestAnimationFrame(f)})(performance.now())})}
/* fx */
function popup(h,mid,cls){const p=$('#pop');document.body.classList.add('mo');p.className='on'+(mid?' mid':'');p.innerHTML=`<div class="sh2 ${cls||''}">${h}</div>`}function closePop(){$('#pop').className='';document.body.classList.remove('mo')}
$('#pop').addEventListener('click',e=>{if(e.target.id==='pop')closePop()});
function beep(f,d){try{const a=window._a||(window._a=new(window.AudioContext||window.webkitAudioContext)()),o=a.createOscillator(),g=a.createGain();o.type='triangle';o.frequency.value=f;g.gain.setValueAtTime(.2,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d+.1);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+d+.12)}catch(e){}}
function celebrate(){const c=$('#cf'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const col=['#f7d99a','#e4b055','#2fd29a','#ffffff','#1c8a64'],cf=[],sp=[];for(let i=0;i<150;i++)cf.push({x:Math.random()*innerWidth,y:-20-Math.random()*innerHeight*.6,vx:(Math.random()-.5)*2,vy:2+Math.random()*3.5,r:Math.random()*6,vr:(Math.random()-.5)*.3,w:5+Math.random()*6,c:col[i%5]});
const burst=()=>{const bx=innerWidth*(.15+Math.random()*.7),by=innerHeight*(.1+Math.random()*.32),g=Math.random()<.5;for(let i=0;i<80;i++){const a=Math.random()*6.283,v=90+Math.random()*260;sp.push({x:bx,y:by,px:bx,py:by,vx:Math.cos(a)*v,vy:Math.sin(a)*v,l:0,m:900+Math.random()*900,c:g?['247,217,154','228,176,85']:['47,210,154','190,255,225']})}};[0,450,950,1500,2100,2800,3400].forEach(t=>setTimeout(burst,t));let f=0,t0=performance.now(),last=t0;(function d(n){const dt=Math.min(.05,(n-last)/1000);last=n;x.clearRect(0,0,c.width,c.height);cf.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.r+=p.vr;x.save();x.translate(p.x,p.y);x.rotate(p.r);x.fillStyle=p.c;x.fillRect(-p.w/2,-p.w/4,p.w,p.w/2);x.restore()});x.globalCompositeOperation='lighter';for(let i=sp.length-1;i>=0;i--){const p=sp[i];p.l+=dt*1000;if(p.l>p.m){sp.splice(i,1);continue}const k=p.l/p.m,d2=Math.pow(.35,dt);p.px=p.x;p.py=p.y;p.vx*=d2;p.vy=p.vy*d2+200*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;x.strokeStyle=`rgba(${p.c[k<.5?0:1]},${1-k})`;x.lineWidth=2.2*(1-k*.6);x.lineCap='round';x.beginPath();x.moveTo(p.px,p.py);x.lineTo(p.x,p.y);x.stroke()}x.globalCompositeOperation='source-over';if(n-t0<5800)requestAnimationFrame(d);else x.clearRect(0,0,c.width,c.height)})(t0)}
function promo(id){const p=PROMOS.find(a=>a.id===id);popup(`<img class="cv" src="assets/${p.img}.jpg" alt=""><div class="bd"><h3>${p.t} ${p.c!=='BOX'?p.c:''}</h3><p>${p.d}</p><button class="btn" id="pa">${p.b}</button><button class="btn gl" onclick="closePop()">Закрыть</button></div>`);$('#pa').onclick=()=>{closePop();location.hash='#'+p.to}}
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.05,rootMargin:'0px 0px -30px 0px'});
function obs(r){r.querySelectorAll('.rv:not(.in)').forEach((e,i)=>{e.style.transitionDelay=Math.min(i%5,4)*70+'ms';io.observe(e)})}
/* feeds drag */
let df=null,dx=0,dl=0,dm=0;
addEventListener('pointerdown',e=>{const f=e.target.closest&&e.target.closest('.feed');if(f&&e.pointerType==='mouse'){df=f;dx=e.clientX;dl=f.scrollLeft;dm=0}});
addEventListener('pointermove',e=>{if(!df)return;const d=e.clientX-dx;dm=Math.max(dm,Math.abs(d));if(dm>5)df.classList.add('dg');df.scrollLeft=dl-d});
addEventListener('pointerup',()=>{if(df){const f=df;df=null;setTimeout(()=>f.classList.remove('dg'),0)}});
addEventListener('scroll',()=>$('#hd').classList.toggle('sc2',scrollY>30),{passive:true});
/* router */
const order=['home','menu','loyalty','cart','profile'],oi=t=>t==='places'?5:order.indexOf(t);
function route(){clearTimeout(qt);closePop();const h=location.hash.slice(1)||'/home',parts=h.split('/');let key=parts[1]||'home';if(key==='about')key='places';const m=key==='product';if(key==='menu'&&parts[2]&&CATS.some(c=>c.id===parts[2])){mcat=parts[2];q0=''}
const tab=m?'menu':(order.includes(key)||key==='places'?key:'home'),prev=hist[hist.length-2],bw=prev===h||(!m&&cur!=='product'&&oi(tab)<oi(cur));if(prev===h)hist.pop();else if(hist[hist.length-1]!==h)hist.push(h);
const bc=document.body.classList;bc.toggle('bw',bw);bc.toggle('fw',!bw);bc.toggle('prof',tab==='profile');bc.toggle('bgp',tab==='places');bc.toggle('bgc',tab==='cart');
const pv=$('#pv video');tab==='profile'?pv.play().catch(()=>{}):pv.pause();
V.innerHTML=m?product(parts[2]):({menu,loyalty,cart,places,profile}[tab]||home)();window.scrollTo(0,0);cur=m?'product':tab;
$('#hd').classList.toggle('sub',m||tab!=='home');$('#hd').classList.remove('sc2');
$('#nav').innerHTML=`<a href="#/home" class="${tab==='home'?'on':''}">${ic('home')}Главная</a><a href="#/menu" class="${tab==='menu'?'on':''}">${ic('menu')}Меню</a><a href="#/loyalty" class="cb ${tab==='loyalty'?'on':''}" aria-label="QR и лояльность">${ic('qr')}</a><a href="#/cart" class="${tab==='cart'?'on':''}">${ic('cart')}Корзина<span class="bdg" id="bdg"></span></a><a href="#/profile" class="${tab==='profile'?'on':''}">${ic('profile')}Профиль</a>`;badge();
if(m)bindProduct(parts[2]);if(tab==='loyalty')bindLoyalty();if(tab==='profile')bindProfile();
V.querySelectorAll('.pm').forEach(b=>b.onclick=()=>{b.classList.add('prs');setTimeout(()=>{b.classList.remove('prs');promo(b.dataset.p)},150)});
V.querySelectorAll('.fa').forEach(b=>b.onclick=()=>b.parentNode.querySelector('.feed').scrollBy({left:+b.dataset.d*260,behavior:'smooth'}));
V.querySelectorAll('.lc .hd').forEach(b=>b.onclick=e=>{if(e.target.closest('a'))return;b.parentNode.classList.toggle('open')});
bindCards(V);
if(tab==='menu'&&!m){$('#qs').oninput=e=>{q0=e.target.value;$('#ml').innerHTML=mlist();bindCards($('#ml'));obs($('#ml'))};V.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{mcat=b.dataset.c;b.parentNode.scrollTo({left:b.offsetLeft-70,behavior:'smooth'});V.querySelectorAll('.chip').forEach(c=>c.classList.toggle('on',c===b));$('#ml').innerHTML=mlist();bindCards($('#ml'));obs($('#ml'))})}
if(tab==='cart'&&C.length){V.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{const l=C[+b.dataset.q];l.q+=+b.dataset.d;if(l.q<1)C.splice(+b.dataset.q,1);save();const y=scrollY;route();scrollTo(0,y)});$('#clr').onclick=()=>{C=[];save();route()};$('#pay').onclick=()=>popup(`<div class="bd"><div class="ic">${ic('lock')}</div><h3>Демо-режим</h3><p>Оплата будет доступна в официальном мобильном приложении iOS / Android</p><button class="btn" onclick="closePop()">Понятно</button></div>`,1)}
obs(V)}
function bindCards(r){r.querySelectorAll('[data-h]').forEach(c=>c.onclick=e=>{const a=e.target.closest('.add');if(a){e.stopPropagation();addCart(a.dataset.a,0,-1,0,a);a.classList.add('ok');setTimeout(()=>a.classList.remove('ok'),900);return}location.hash=c.dataset.h})}
$('#app').insertAdjacentHTML('afterbegin','<div id="pv"><video src="assets/vp.mp4" poster="assets/vp.jpg" muted loop playsinline preload="none"></video></div>');
$('#ht').innerHTML=lgo()+'<span>Кофейня N5</span>';$('#hc').innerHTML=ic('refresh');$('#hc').onclick=()=>location.reload();$('#bk').innerHTML=ic('back');
$('#bk').onclick=()=>hist.length>1?history.back():(location.hash='#/home');addEventListener('hashchange',route);route();
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
