const $=s=>document.querySelector(s),V=$('#view'),fm=n=>n.toLocaleString('ru-RU')+' ₸';
const P={home:'<path d="M3 11l9-8 9 8v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/>',menu:'<path d="M5 8h12v6a5 5 0 0 1-5 5h-2a5 5 0 0 1-5-5zM17 9h2a2 2 0 0 1 0 5h-2M8 2v3M12 2v3"/>',cart:'<path d="M3 4h2l2.4 11h10.2L20 7H6.5"/><circle cx="9" cy="19.5" r="1.4"/><circle cx="17" cy="19.5" r="1.4"/>',places:'<path d="M12 21s7-6 7-12a7 7 0 0 0-14 0c0 6 7 12 7 12z"/><circle cx="12" cy="9" r="2.5"/>',profile:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',phone:'<path d="M5 4h4l2 5-2.5 1.5a11 11 0 0 0 5 5L15 13l5 2v4a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2z"/>',back:'<path d="M15 5l-7 7 7 7"/>',chev:'<path d="M9 5l7 7-7 7"/>',search:'<circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"/>',plus:'<path d="M12 5v14M5 12h14"/>',map:'<path d="M9 4L3 6v14l6-2 6 2 6-2V4l-6 2zM9 4v14M15 6v14"/>',star:'<path d="M12 2.5l2.9 6.1 6.6.8-4.9 4.6 1.3 6.6L12 17.3 6.1 20.6l1.3-6.6L2.5 9.4l6.6-.8z"/>',lock:'<rect x="5" y="11" width="14" height="9" rx="2"/><path d="M8 11V8a4 4 0 0 1 8 0v3"/>',qr:'<path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h2v2h-2zM18 14h2v6h-4M14 18h2"/>',ext:'<path d="M7 17L17 7M8 7h9v9"/>',insta:'<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><path d="M17.5 6.5h.01"/>'};
const ic=(n,c='')=>`<svg class="i ${c}" viewBox="0 0 24 24">${P[n]}</svg>`;
const lgo=(c='')=>`<svg class="lg ${c}"><use href="#lgo" width="100%" height="100%"/></svg>`;
(function(){const s=$('#lgo');s.setAttribute('viewBox',LOGO.vb.join(' '));s.innerHTML=`<path d="${LOGO.d}"/>`})();
let S={cups:0,total:0,gifts:0,hist:[],id:'N5-'+Math.floor(1000+Math.random()*9000)},C=[];
try{S=Object.assign(S,JSON.parse(localStorage.getItem('k5')||'{}'));C=JSON.parse(localStorage.getItem('k5c')||'[]')}catch(e){}
const save=()=>{try{localStorage.setItem('k5',JSON.stringify(S));localStorage.setItem('k5c',JSON.stringify(C))}catch(e){}};
let uid=0,mcat='all',tm=null,hist=[],cur='',tt=null,q0='';
const find=id=>ALL.find(a=>a.id===id),line=l=>{const x=find(l.id);return x.s[l.z][1]+(l.y>=0?250:0)+(l.m?690:0)},cnt=()=>C.reduce((a,l)=>a+l.q,0),sum=()=>C.reduce((a,l)=>a+line(l)*l.q,0);
function fly(el){const nb=$('nav .cb');if(!el||!nb)return;const a=el.getBoundingClientRect(),b=nb.getBoundingClientRect(),d=document.createElement('div');d.className='fly';d.style.left=a.left+a.width/2-8+'px';d.style.top=a.top+a.height/2-8+'px';document.body.appendChild(d);d.animate([{transform:'translate(0,0) scale(1)',opacity:1},{transform:`translate(${b.left+b.width/2-a.left-a.width/2}px,${b.top+b.height/2-a.top-a.height/2}px) scale(.3)`,opacity:.4}],{duration:700,easing:'cubic-bezier(.5,-.3,.7,1)'}).onfinish=()=>d.remove()}
function addCart(id,z=0,y=-1,m=0,el){const l=C.find(l=>l.id===id&&l.z===z&&l.y===y&&l.m===m);l?l.q++:C.push({id,z,y,m,q:1});save();fly(el);setTimeout(()=>badge(true),600);toast('Добавлено: '+find(id).n)}
function badge(p){const b=$('#bdg');if(!b)return;b.textContent=cnt();b.style.display=cnt()?'':'none';if(p){b.classList.remove('pop');void b.offsetWidth;b.classList.add('pop')}}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('on');clearTimeout(tt);tt=setTimeout(()=>e.classList.remove('on'),1800)}
/* cup & qr */
function cup(lv=1){const i=++uid;return`<svg class="cp" viewBox="0 0 100 128"><defs><clipPath id="cc${i}"><path d="M14 30h72l-8 90a6 6 0 0 1-6 5H28a6 6 0 0 1-6-5z"/></clipPath><pattern id="cs${i}" width="12" height="10" patternUnits="userSpaceOnUse"><rect width="6" height="10" fill="#f4efe4"/><rect x="6" width="6" height="10" fill="#0f5a40"/></pattern><linearGradient id="cl${i}" x1="0" y1="1" x2="0" y2="0"><stop offset="0" stop-color="#0f5a40"/><stop offset=".6" stop-color="#2fd29a"/><stop offset="1" stop-color="#f7d99a"/></linearGradient></defs><g style="filter:drop-shadow(0 8px 10px #000b)"><rect x="9" y="16" width="82" height="16" rx="6" fill="#16372b"/><rect x="16" y="8" width="68" height="9" rx="4" fill="#0b2018"/><g clip-path="url(#cc${i})"><rect y="30" width="100" height="98" fill="#16231d"/><rect y="30" width="100" height="98" fill="url(#cs${i})" opacity=".2"/><rect class="lv" y="30" width="100" height="98" fill="url(#cl${i})" style="transform-origin:50% 100%;transform:scaleY(${lv});transition:transform 1.5s cubic-bezier(.34,1.4,.64,1)"/><rect y="30" width="100" height="98" fill="url(#cs${i})" opacity="${lv?.72:0}"/></g></g><circle cx="50" cy="78" r="23" fill="#07130e" stroke="#e4b055" stroke-width="1.4"/><use href="#lgo" x="29" y="57" width="42" height="42" fill="#f7d99a" fill-rule="evenodd"/></svg>`}
function qr(tok){let s=0;for(const c of tok)s=(s*31+c.charCodeAt(0))>>>0;const r=()=>(s=(s*1664525+1013904223)>>>0)/4294967296,N=29;let o='';const fin=(x,y)=>{o+=`<rect x="${x}" y="${y}" width="7" height="7" rx="1.8" fill="#0b2a20"/><rect x="${x+1}" y="${y+1}" width="5" height="5" rx="1.2" fill="#fff"/><rect x="${x+2}" y="${y+2}" width="3" height="3" rx="1" fill="#0b2a20"/>`};for(let y=0;y<N;y++)for(let x=0;x<N;x++){if((x<8&&y<8)||(x>20&&y<8)||(x<8&&y>20)||(Math.abs(x-14)<5.6&&Math.abs(y-14)<5.6))continue;if(r()>.5)o+=`<rect x="${x+.08}" y="${y+.08}" width=".84" height=".84" rx=".3" fill="#0b2a20"/>`}fin(0,0);fin(22,0);fin(0,22);return`<svg viewBox="0 0 29 29">${o}<circle cx="14.5" cy="14.5" r="4.9" fill="#07130e"/><circle cx="14.5" cy="14.5" r="4.9" fill="none" stroke="#e4b055" stroke-width=".25"/><use href="#lgo" x="10.7" y="10.7" width="7.6" height="7.6" fill="#f7d99a" fill-rule="evenodd"/></svg>`}
const pr=x=>(x.s.length>1?'от ':'')+fm(x.s[0][1]),tg=x=>x.tag?`<span class="tag ${x.tag}">${x.tag==='hit'?'HIT':'NEW'}</span>`:'';
const sec=(s,t,a='')=>`<div class="sh rv"><div><small>${s}</small><h2>${t}</h2></div>${a}</div>`;
const feed=h=>`<div class="fd rv"><button class="fa l" data-d="-1" aria-label="Назад">${ic('back')}</button><div class="feed">${h}</div><button class="fa r" data-d="1" aria-label="Вперёд">${ic('chev')}</button></div>`;
function status(l){const n=new Date(),h=n.getHours()+n.getMinutes()/60,d=n.getDay(),c=(l.c2&&(d===5||d===6||d===0))?l.c2:l.c,p=v=>String(v%24).padStart(2,'0')+':00';return h>=l.o&&h<c?`<span class="st o">Открыто до ${p(c)}</span>`:`<span class="st c">Закрыто · с ${p(l.o)}</span>`}
function locCard(l){const ph=l.tel?`<a class="btn gl" href="tel:${l.tel}">${ic('phone')}Позвонить</a>`:'';return`<div class="lc rv"><div class="hd"><img class="th" src="assets/${l.img}.jpg" alt="${l.n}" loading="lazy"><div><h3>${l.n}</h3><div class="ad">${l.a}</div><div class="mt">${status(l)}<a class="g2" target="_blank" rel="noopener" href="${l.g}">${ic('map')}2GIS</a></div></div>${ic('chev','ch')}</div><div class="xp"><img src="assets/${l.img}.jpg" alt=""><div class="bd"><div class="row"><span>Адрес</span><b>${l.a}</b></div><div class="row"><span>Режим работы</span><b>${l.h}</b></div>${l.ph?`<div class="row"><span>Телефон</span><b><a href="tel:${l.tel}">${l.ph}</a></b></div>`:''}${l.r?`<div class="rt"><b>${l.r}</b>${ic('star')}<small>${l.aw}</small></div>`:''}<div class="acts"><a class="btn" target="_blank" rel="noopener" href="${l.g}">${ic('map')}Открыть в 2GIS</a>${ph}</div></div></div></div>`}
/* pages */
function home(){const nw=ALL.filter(x=>x.tag==='new'),m=LOCS[0];return`<div class="pg"><div class="hero"><video src="assets/v1.mp4" poster="assets/v1.jpg" autoplay muted loop playsinline></video><div class="hc"><div class="ey">${ic('places')}Павлодар</div><h1>Не просто<br><em>кофе</em></h1><p>Авторские напитки, свежая выпечка и десерты. Каждый 6-й напиток — в подарок.</p><div class="bt"><a class="btn" href="#/menu">Смотреть меню</a><a class="btn gl" href="#/places">Адреса</a></div></div></div>
<a class="card loy rv" href="#/profile">${cup(Math.min(1,S.cups/5))}<div style="flex:1"><h3>Карта гостя 5+1</h3><p>${S.cups<5?'До подарка осталось '+(5-S.cups):'Следующий напиток — бесплатно'}</p><div class="bar"><i style="width:${S.cups/5*100}%"></i></div></div></a>
${sec('Предложения','Акции')}${feed(PROMOS.map(p=>`<button class="pm" data-p="${p.id}"><img src="assets/${p.img}.jpg" alt="${p.t}"><span class="ch">${p.c}</span><div><b>${p.t}</b><small>${p.s}</small></div></button>`).join(''))}
${sec('Выбирайте','Категории')}<div class="bento rv">${BENTO.map((b,i)=>`<a class="bn bt${i+1}" href="#/menu/${b[0]}"><img src="assets/${b[2]}.jpg" alt=""><span>${b[1]}</span>${ic('chev')}</a>`).join('')}</div>
${sec('Только что в меню','Новинки','<a href="#/menu">Всё меню</a>')}${feed(nw.map(x=>`<div class="nw" data-h="#/product/${x.id}"><div class="im"><img src="assets/${x.img}.jpg" alt="${x.n}">${tg(x)}<button class="add" data-a="${x.id}" aria-label="Добавить">${ic('plus')}</button></div><b>${x.n}</b><small>${pr(x)}</small></div>`).join(''))}
${sec('Заходите','Главная кофейня')}${locCard(m)}<a class="btn gl rv" href="#/places" style="margin-top:4px">${ic('places')}Все адреса и режим работы</a></div>`}
function mlist(){const q=q0.trim().toLowerCase(),L=(mcat==='all'?CATS:CATS.filter(c=>c.id===mcat)).map(c=>({...c,items:c.items.filter(x=>!q||x.n.toLowerCase().includes(q))})).filter(c=>c.items.length);return L.length?L.map(c=>`${sec(c.items.length+' поз.',c.n)}<div class="grid">${c.items.map(x=>`<div class="mc rv" data-h="#/product/${x.id}"><div class="im"><img loading="lazy" src="assets/${x.img}.jpg" alt="${x.n}">${tg(x)}<span class="pr">${pr(x)}</span><button class="add" data-a="${x.id}" title="+ Добавить" aria-label="Добавить">${ic('plus')}</button></div><div class="bd"><b>${x.n}</b><small>${x.s.map(s=>s[0]).join(' · ')}</small></div></div>`).join('')}</div>`).join(''):'<p class="no">Ничего не найдено</p>'}
function menu(){return`<div class="pg"><div class="srch">${ic('search')}<input id="qs" type="search" placeholder="Поиск по меню" value="${q0}"></div><div class="chips">${[{id:'all',n:'Всё'},...CATS].map(c=>`<button class="chip ${c.id===mcat?'on':''}" data-c="${c.id}">${c.n}</button>`).join('')}</div><div id="ml">${mlist()}</div><p class="cap" style="margin-top:22px">Если у вас есть аллергия — предупредите кассира.</p></div>`}
function product(id){const x=find(id);if(!x)return'<div class="pg"><p class="no">Позиция не найдена</p></div>';return`<div class="pg pd"><div class="big"><img src="assets/${x.img}.jpg" alt="${x.n}"></div><div class="sheet"><h1>${x.n}</h1><p>${x.d||x.cn}</p><div class="lab">${x.s.length>1?'Объём':'Порция'}</div><div class="opt" id="sz">${x.s.map((s,i)=>`<button class="pill ${i?'':'on'}" data-i="${i}">${s[0]} · ${fm(s[1])}</button>`).join('')}</div>
${x.drink?`<div class="lab">Сироп +250 ₸</div><div class="opt" id="sy"><button class="pill on" data-i="-1">Без сиропа</button>${SYR.map((s,i)=>`<button class="pill" data-i="${i}">${s}</button>`).join('')}</div><div class="lab">Молоко</div><div class="opt" id="ml2"><button class="pill on" data-i="0">Обычное</button><button class="pill" data-i="1">Альтернативное +690 ₸</button></div>`:''}
<div class="sb"><div class="tt"><small>Итого</small><b id="tt"></b></div><button class="btn" id="addp">${ic('cart')}В корзину</button></div></div></div>`}
function bindProduct(id){const x=find(id);if(!x)return;let z=0,y=-1,m=0;const up=()=>$('#tt').textContent=fm(x.s[z][1]+(y>=0?250:0)+(m?690:0));const pick=(q,f)=>{const e=$(q);e&&e.addEventListener('click',ev=>{const b=ev.target.closest('.pill');if(!b)return;e.querySelectorAll('.pill').forEach(p=>p.classList.remove('on'));b.classList.add('on');f(+b.dataset.i);up()})};pick('#sz',i=>z=i);pick('#sy',i=>y=i);pick('#ml2',i=>m=i);up();$('#addp').onclick=e=>addCart(id,z,y,m,e.currentTarget)}
function cart(){if(!C.length)return`<div class="pg"><div class="empty">${ic('cart')}<h3>Корзина пуста</h3><p style="margin-bottom:22px">Добавьте напитки и выпечку из меню</p><a class="btn" href="#/menu">Перейти в меню</a></div></div>`;
return`<div class="pg"><div class="card rv">${C.map((l,i)=>{const x=find(l.id);return`<div class="ci"><img src="assets/${x.img}.jpg" alt=""><div><b>${x.n}</b><small>${x.s[l.z][0]}${l.y>=0?' · '+SYR[l.y]:''}${l.m?' · альт. молоко':''}</small><div class="q"><button data-q="${i}" data-d="-1" aria-label="Меньше">−</button><span>${l.q}</span><button data-q="${i}" data-d="1" aria-label="Больше">+</button></div></div><em>${fm(line(l)*l.q)}</em></div>`}).join('')}</div>
<div class="card rv" style="margin-top:14px"><div class="row"><span>Позиций</span><b>${cnt()}</b></div><div class="tot"><span>Итого</span><b>${fm(sum())}</b></div></div><button class="btn rv" id="pay" style="margin-top:16px">${ic('lock')}Оформить и оплатить</button><button class="btn gl rv" id="clr" style="margin-top:10px">Очистить корзину</button></div>`}
function mapArt(){let g='';for(let i=0;i<9;i++)g+=`<path d="M${-20+i*60} 0L${40+i*60} 190" stroke="#1c5a44" stroke-width="${i%3?1:2}" opacity=".5"/>`;for(let i=0;i<5;i++)g+=`<path d="M0 ${20+i*42}L400 ${i*42-6}" stroke="#1c5a44" stroke-width="${i%2?1:2}" opacity=".5"/>`;return`<svg class="mp" viewBox="0 0 400 190" preserveAspectRatio="xMidYMid slice"><rect width="400" height="190" fill="#0a1d16"/>${g}<path d="M-10 150C80 110 150 170 240 120S370 90 420 100" fill="none" stroke="#14705c" stroke-width="16" opacity=".55"/><circle cx="215" cy="70" r="46" fill="#2fd29a" opacity=".12"/><circle cx="215" cy="70" r="22" fill="#2fd29a" opacity=".2"/><path d="M215 92s14-12 14-26a14 14 0 0 0-28 0c0 14 14 26 14 26z" fill="#e4b055"/><circle cx="215" cy="66" r="5" fill="#0a1d16"/><rect width="400" height="190" fill="url(#mg)"/><defs><linearGradient id="mg" x1="0" y1="0" x2="0" y2="1"><stop offset=".35" stop-color="#050907" stop-opacity="0"/><stop offset="1" stop-color="#050907" stop-opacity=".92"/></linearGradient></defs></svg>`}
function places(){const ph=['t1','in1','wall','in2','t3','note','t4','latte','choc','tea','honey','berry','brulee','croissant'];return`<div class="pg"><div class="sh" style="margin-top:4px"><div><small>Павлодар · ${LOCS.length} точек</small><h2>Найти кофейню</h2></div></div>
<div class="mapc rv">${mapArt()}<div class="mi"><div><h3>Все точки на карте</h3><small>Откроется в 2GIS</small></div><a class="g2" style="padding:11px 16px;font-size:14px" target="_blank" rel="noopener" href="${G('Кофейня N5 Павлодар')}">${ic('map')}2GIS</a></div></div>
${sec('Режим работы','Наши точки')}${LOCS.map(locCard).join('')}
${sec('Фирменная упаковка','Стаканчики и пакеты')}${feed(CUPS.map(c=>`<div class="nw" style="width:200px"><div class="im" style="height:260px"><img src="assets/${c}.jpg" alt=""></div></div>`).join(''))}
${sec('Живая атмосфера','Видео')}<div class="vid rv">${[1,2,3,4].map(i=>`<div class="v"><video src="assets/v${i}.mp4" poster="assets/v${i}.jpg" autoplay muted loop playsinline></video></div>`).join('')}</div>
${sec('Интерьер и подача','Фотогалерея')}<div class="phg">${ph.map(p=>`<img class="rv" loading="lazy" src="assets/${p}.jpg" alt="">`).join('')}</div>
${sec('Мы в сети','Контакты')}<div class="card rv"><div class="row"><span>Instagram</span><b><a target="_blank" rel="noopener" href="https://instagram.com/pekarnya_n5">@pekarnya_n5</a></b></div><div class="row"><span>Бронь столов</span><b>свободная рассадка</b></div><div class="row"><span>С питомцами</span><b>можно, кроме семейного зала</b></div></div></div>`}
function profile(){const t=S.total,st=t>=20?'Знаток N5':t>=6?'Постоянный гость':'Новый гость';return`<div class="pg"><div class="card pcard pf rv"><div class="av">${lgo()}</div><div><h3 style="font:700 24px var(--ff)">Гость</h3><div class="bad">${st}</div><p style="color:var(--t2);font-size:13px;margin-top:6px">Карта ${S.id}</p></div></div>
<div class="stat rv"><div><b>${t}</b><span>напитков</span></div><div><b>${S.gifts}</b><span>подарков</span></div><div><b>${5-S.cups}</b><span>до подарка</span></div></div>
${sec('Купи 5 — 6-й в подарок','Карта 5+1')}<div class="card pcard rv"><div class="cups" id="cups"></div></div>
<div class="card pcard rv" style="margin-top:14px"><div class="qr" id="qb"><span id="qs2">${qr(S.id)}</span><div class="laser"></div></div><p class="cap">Покажите код бариста</p><button class="btn" id="sc">${ic('qr')}[Демо] Сканировать у бариста</button></div>
${sec('Последние начисления','История')}<div class="card pcard rv">${S.hist.length?S.hist.slice(0,12).map(h=>`<div class="row"><span>${new Date(h.t).toLocaleString('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</span><b>${h.x}</b></div>`).join(''):'<p class="cap" style="margin:0">Пока пусто — нажмите «Сканировать у бариста».</p>'}</div>
<button class="btn gl rv" id="rs" style="margin-top:16px">Сбросить демо-данные</button></div>`}
function cups(an){$('#cups').innerHTML=[0,1,2,3,4,5].map(i=>`<div>${cup(i<S.cups&&an!==i?1:0)}<small>${i===5?'в подарок':i+1+'-й напиток'}</small></div>`).join('');if(an!=null)setTimeout(()=>{const c=document.querySelectorAll('#cups .cp')[an];if(!c)return;c.querySelector('.lv').style.transform='scaleY(1)';c.animate([{transform:'scale(1)'},{transform:'scale(1.2) rotate(-4deg)'},{transform:'scale(1)'}],{duration:900,easing:'ease-out'})},80)}
function bindProfile(){cups();tm=setInterval(()=>{const q=$('#qs2');q&&(q.innerHTML=qr(S.id+Date.now()))},30000);const b=$('#sc');b.onclick=()=>{b.disabled=true;const q=$('#qb');q.classList.add('scan');beep(500,.08);setTimeout(()=>{q.classList.remove('scan');q.classList.add('ok');beep(880,.15);setTimeout(()=>beep(1320,.25),130);navigator.vibrate&&navigator.vibrate([60,40,150]);S.cups++;S.total++;const n=S.cups;S.hist.unshift({t:Date.now(),x:n>=6?'Шестой напиток в подарок':'Напиток №'+n+' зачтён'});cups(n-1);save();setTimeout(()=>{q.classList.remove('ok');b.disabled=false},800);if(n>=6){S.gifts++;setTimeout(()=>{confetti();popup(`<div class="bd">${cup(1)}<h3>Поздравляем!</h3><p>Шестой напиток — в подарок! Новая карта уже ждёт вас: копите следующие 5.</p><button class="btn" onclick="closePop()">Ура!</button></div>`,1);S.cups=0;save();cups()},1700)}},3300)};$('#rs').onclick=()=>{S={cups:0,total:0,gifts:0,hist:[],id:S.id};save();route()}}
/* fx */
function popup(h,mid){const p=$('#pop');p.className='on'+(mid?' mid':'');p.innerHTML=`<div class="sh2">${h}</div>`}function closePop(){$('#pop').className=''}
$('#pop').addEventListener('click',e=>{if(e.target.id==='pop')closePop()});
function beep(f,d){try{const a=window._a||(window._a=new(window.AudioContext||window.webkitAudioContext)()),o=a.createOscillator(),g=a.createGain();o.type='triangle';o.frequency.value=f;g.gain.setValueAtTime(.2,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d+.1);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+d+.12)}catch(e){}}
function confetti(){const c=$('#cf'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const col=['#f7d99a','#e4b055','#2fd29a','#fff','#1c8a64'],Pn=[];for(let k=0;k<4;k++)for(let i=0;i<60;i++){const a=-Math.PI/2+(Math.random()-.5)*1.4,v=8+Math.random()*10;Pn.push({x:innerWidth*(.2+k*.2),y:innerHeight*.7,vx:Math.cos(a)*v,vy:Math.sin(a)*v,c:col[i%5],s:3+Math.random()*5,d:k*14})}let f=0;(function d(){x.clearRect(0,0,c.width,c.height);Pn.forEach(p=>{if(f<p.d)return;p.x+=p.vx;p.y+=p.vy;p.vy+=.3;p.vx*=.99;x.fillStyle=p.c;x.fillRect(p.x,p.y,p.s,p.s*1.7)});if(++f<200)requestAnimationFrame(d);else x.clearRect(0,0,c.width,c.height)})()}
function promo(id){const p=PROMOS.find(a=>a.id===id);popup(`<img class="cv" src="assets/${p.img}.jpg" alt=""><div class="bd"><h3>${p.t} ${p.c!=='BOX'?p.c:''}</h3><p>${p.d}</p><button class="btn" id="pa">${p.b}</button><button class="btn gl" onclick="closePop()">Закрыть</button></div>`);$('#pa').onclick=()=>{closePop();location.hash='#'+p.to}}
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.05,rootMargin:'0px 0px -30px 0px'});
function obs(r){r.querySelectorAll('.rv:not(.in)').forEach((e,i)=>{e.style.transitionDelay=Math.min(i%5,4)*70+'ms';io.observe(e)})}
/* feeds drag */
let df=null,dx=0,dl=0,dm=0;
addEventListener('pointerdown',e=>{const f=e.target.closest&&e.target.closest('.feed');if(f&&e.pointerType==='mouse'){df=f;dx=e.clientX;dl=f.scrollLeft;dm=0}});
addEventListener('pointermove',e=>{if(!df)return;const d=e.clientX-dx;dm=Math.max(dm,Math.abs(d));if(dm>5)df.classList.add('dg');df.scrollLeft=dl-d});
addEventListener('pointerup',()=>{if(df){const f=df;df=null;setTimeout(()=>f.classList.remove('dg'),0)}});
addEventListener('scroll',()=>$('#hd').classList.toggle('sc2',scrollY>30),{passive:true});
/* router */
const order=['home','menu','cart','places','profile'],TT={menu:'Меню',cart:'Корзина',places:'Адреса',profile:'Профиль'};
function route(){clearInterval(tm);closePop();const h=location.hash.slice(1)||'/home',parts=h.split('/');let key=parts[1]||'home';if(key==='about')key='places';if(key==='loyalty')key='profile';const m=key==='product';if(key==='menu'&&parts[2]&&CATS.some(c=>c.id===parts[2])){mcat=parts[2];q0=''}
const tab=m?'menu':(order.includes(key)?key:'home'),prev=hist[hist.length-2],bw=prev===h||(!m&&cur!=='product'&&order.indexOf(tab)<order.indexOf(cur));if(prev===h)hist.pop();else if(hist[hist.length-1]!==h)hist.push(h);
document.body.classList.toggle('bw',bw);document.body.classList.toggle('fw',!bw);document.body.classList.toggle('prof',tab==='profile');
const pv=$('#pv video');tab==='profile'?pv.play().catch(()=>{}):pv.pause();
V.innerHTML=m?product(parts[2]):({menu,cart,places,profile}[tab]||home)();window.scrollTo(0,0);cur=m?'product':tab;
$('#hd').classList.toggle('sub',m||tab!=='home');$('#hd').classList.remove('sc2');$('#ht').innerHTML=tab==='home'?lgo()+'<span>Кофейня N5</span>':(m?'':(TT[tab]||''));
$('#hc').innerHTML=ic('phone');$('#bk').innerHTML=ic('back');
$('#nav').innerHTML=`<a href="#/home" class="${tab==='home'?'on':''}">${ic('home')}Главная</a><a href="#/menu" class="${tab==='menu'?'on':''}">${ic('menu')}Меню</a><a href="#/cart" class="cb ${tab==='cart'?'on':''}" aria-label="Корзина">${ic('cart')}<span class="bdg" id="bdg"></span></a><a href="#/places" class="${tab==='places'?'on':''}">${ic('places')}Адреса</a><a href="#/profile" class="${tab==='profile'?'on':''}">${ic('profile')}Профиль</a>`;badge();
if(m)bindProduct(parts[2]);if(tab==='profile')bindProfile();
V.querySelectorAll('.pm').forEach(b=>b.onclick=()=>promo(b.dataset.p));
V.querySelectorAll('.fa').forEach(b=>b.onclick=()=>b.parentNode.querySelector('.feed').scrollBy({left:+b.dataset.d*260,behavior:'smooth'}));
V.querySelectorAll('.lc .hd').forEach(b=>b.onclick=e=>{if(e.target.closest('a'))return;b.parentNode.classList.toggle('open')});
bindCards(V);
if(tab==='menu'&&!m){$('#qs').oninput=e=>{q0=e.target.value;$('#ml').innerHTML=mlist();bindCards($('#ml'));obs($('#ml'))};V.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{mcat=b.dataset.c;V.querySelectorAll('.chip').forEach(c=>c.classList.toggle('on',c===b));$('#ml').innerHTML=mlist();bindCards($('#ml'));obs($('#ml'))})}
if(tab==='cart'&&C.length){V.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{const l=C[+b.dataset.q];l.q+=+b.dataset.d;if(l.q<1)C.splice(+b.dataset.q,1);save();const y=scrollY;route();scrollTo(0,y)});$('#clr').onclick=()=>{C=[];save();route()};$('#pay').onclick=()=>popup(`<div class="bd"><div class="ic">${ic('lock')}</div><h3>Демо-режим</h3><p>Оплата будет доступна в официальном мобильном приложении iOS / Android</p><button class="btn" onclick="closePop()">Понятно</button></div>`,1)}
obs(V)}
function bindCards(r){r.querySelectorAll('[data-h]').forEach(c=>c.onclick=e=>{const a=e.target.closest('.add');if(a){e.stopPropagation();addCart(a.dataset.a,0,-1,0,a);a.classList.add('ok');setTimeout(()=>a.classList.remove('ok'),900);return}location.hash=c.dataset.h})}
$('#app').insertAdjacentHTML('afterbegin','<div id="pv"><video src="assets/vp.mp4" poster="assets/vp.jpg" muted loop playsinline preload="none"></video></div>');
$('#bk').onclick=()=>hist.length>1?history.back():(location.hash='#/home');addEventListener('hashchange',route);route();
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
