const $=s=>document.querySelector(s),V=$('#view'),fm=n=>n.toLocaleString('ru-RU')+' ₸';
const P={home:'<path d="M3 11l9-8 9 8v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/>',menu:'<path d="M5 8h12v6a5 5 0 0 1-5 5h-2a5 5 0 0 1-5-5zM17 9h2a2 2 0 0 1 0 5h-2M8 2v3M12 2v3"/>',loyalty:'<rect x="3" y="5" width="18" height="14" rx="3"/><path d="M3 10h18M7 15h4"/>',cart:'<path d="M3 4h2l2.4 11h10.2L20 7H6.5"/><circle cx="9" cy="19.5" r="1.4"/><circle cx="17" cy="19.5" r="1.4"/>',about:'<path d="M12 21s7-6 7-12a7 7 0 0 0-14 0c0 6 7 12 7 12z"/><circle cx="12" cy="9" r="2.5"/>',profile:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',phone:'<path d="M5 4h4l2 5-2.5 1.5a11 11 0 0 0 5 5L15 13l5 2v4a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2z"/>',back:'<path d="M15 5l-7 7 7 7"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',paw:'<circle cx="7" cy="10" r="2"/><circle cx="17" cy="10" r="2"/><circle cx="10" cy="5.5" r="2"/><circle cx="14" cy="5.5" r="2"/><path d="M12 12c-3 0-5 3-5 5.5 0 1.5 1.5 2 3 1.5 1.2-.4 1.8-.4 4 0 1.5.4 3 0 3-1.5C17 15 15 12 12 12z"/>',play:'<path d="M8 5l11 7-11 7z"/>',insta:'<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><path d="M17.5 6.5h.01"/>',qr:'<path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h2v2h-2zM18 14h2v6h-4M14 18h2"/>',check:'<path d="M5 12l5 5 9-10"/>',chev:'<path d="M9 5l7 7-7 7"/>',star:'<path d="M12 2.5l2.9 6.1 6.6.8-4.9 4.6 1.3 6.6L12 17.3 6.1 20.6l1.3-6.6L2.5 9.4l6.6-.8z"/>',lock:'<rect x="5" y="11" width="14" height="9" rx="2"/><path d="M8 11V8a4 4 0 0 1 8 0v3"/>',pin:'<path d="M12 21s7-6 7-12a7 7 0 0 0-14 0c0 6 7 12 7 12z"/><circle cx="12" cy="9" r="2.5"/>'};
const ic=n=>`<svg class="i" viewBox="0 0 24 24">${P[n]}</svg>`;
const NAV=[['home','Главная'],['menu','Меню'],['loyalty','5+1'],['cart','Корзина'],['about','Кофейня'],['profile','Профиль']];
let S={cups:0,total:0,gifts:0,hist:[],id:'N5-'+Math.floor(1000+Math.random()*9000)},C=[];
try{S=Object.assign(S,JSON.parse(localStorage.getItem('k5')||'{}'));C=JSON.parse(localStorage.getItem('k5c')||'[]')}catch(e){}
const save=()=>{try{localStorage.setItem('k5',JSON.stringify(S));localStorage.setItem('k5c',JSON.stringify(C))}catch(e){}};
let uid=0,mcat='all',tm=null,hist=[],cur='',tt=null;
const find=id=>ALL.find(a=>a.id===id),line=l=>{const x=find(l.id);return x.s[l.z][1]+(l.y>=0?250:0)+(l.m?690:0)},cnt=()=>C.reduce((a,l)=>a+l.q,0),sum=()=>C.reduce((a,l)=>a+line(l)*l.q,0);
function addCart(id,z=0,y=-1,m=0){const l=C.find(l=>l.id===id&&l.z===z&&l.y===y&&l.m===m);l?l.q++:C.push({id,z,y,m,q:1});save();badge(true);toast('Добавлено в корзину: '+find(id).n)}
function badge(p){const b=$('#bdg');if(!b)return;b.textContent=cnt();b.style.display=cnt()?'':'none';if(p){b.classList.remove('pop');void b.offsetWidth;b.classList.add('pop')}}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('on');clearTimeout(tt);tt=setTimeout(()=>e.classList.remove('on'),1700)}
/* logo */
function logo(){return`<svg class="lg" viewBox="0 0 447 447"><image class="im" href="assets/logo_kof.png" width="447" height="447"/><path class="o" pathLength="1" d="${LOGO.kof}"/><circle class="sp" r="4" cx="-20" cy="-20"/></svg>`}
function fitLogo(s){const b=s.querySelector('.o').getBBox(),sz=Math.max(b.width,b.height)+30;s.setAttribute('viewBox',`${b.x+b.width/2-sz/2} ${b.y+b.height/2-sz/2} ${sz} ${sz}`)}
function burn(s,dur=2800){fitLogo(s);const sp=s.querySelector('.sp');let best=null,L=0;s.querySelectorAll('path.o').forEach(p=>{const l=p.getTotalLength();if(l>L){L=l;best=p}});const t0=performance.now();(function f(n){const t=Math.min(1,(n-t0)/dur),p=t<.5?2*t*t:1-2*(1-t)*(1-t),pt=best.getPointAtLength(p*L);sp.setAttribute('cx',pt.x);sp.setAttribute('cy',pt.y);if(t<1)requestAnimationFrame(f);else{sp.style.display='none';s.classList.add('done')}})(t0)}
/* cup */
function cup(lv=1,txt){const i=++uid;return`<svg class="cp" viewBox="0 0 100 128"><defs><clipPath id="cc${i}"><path d="M14 30h72l-8 90a6 6 0 0 1-6 5H28a6 6 0 0 1-6-5z"/></clipPath><clipPath id="cb${i}"><circle cx="50" cy="78" r="21"/></clipPath><pattern id="cs${i}" width="12" height="10" patternUnits="userSpaceOnUse"><rect width="6" height="10" fill="#fff"/><rect x="6" width="6" height="10" fill="#14231d"/></pattern><linearGradient id="cl${i}" x1="0" y1="1" x2="0" y2="0"><stop offset="0" stop-color="#0f4c3a"/><stop offset="1" stop-color="#e6c77a"/></linearGradient></defs><g style="filter:drop-shadow(0 6px 8px #0f4c3a44)"><rect x="9" y="16" width="82" height="16" rx="6" fill="#2d7a5c"/><rect x="16" y="8" width="68" height="9" rx="4" fill="#0f4c3a"/><g clip-path="url(#cc${i})"><rect y="30" width="100" height="98" fill="#eef2ef"/><rect class="lv" y="30" width="100" height="98" fill="url(#cl${i})" style="transform-origin:50% 100%;transform:scaleY(${lv});transition:transform 1.5s cubic-bezier(.34,1.4,.64,1)"/><rect y="30" width="100" height="98" fill="url(#cs${i})" opacity="${lv?.7:.16}"/></g></g><circle cx="50" cy="78" r="23" fill="#fff"/><image href="assets/logo_kof.png" x="17" y="45" width="66" height="66" clip-path="url(#cb${i})"/></svg>`}
function qr(tok){let s=0;for(const c of tok)s=(s*31+c.charCodeAt(0))>>>0;const r=()=>(s=(s*1664525+1013904223)>>>0)/4294967296,N=25;let o='';const fd=(x,y)=>{o+=`<rect x="${x}" y="${y}" width="7" height="7" fill="#0f4c3a"/><rect x="${x+1}" y="${y+1}" width="5" height="5" fill="#fff"/><rect x="${x+2}" y="${y+2}" width="3" height="3" fill="#0f4c3a"/>`};for(let y=0;y<N;y++)for(let x=0;x<N;x++){if((x<8&&y<8)||(x>16&&y<8)||(x<8&&y>16))continue;if(r()>.5)o+=`<rect x="${x}" y="${y}" width="1" height="1" fill="#0f4c3a"/>`}fd(0,0);fd(18,0);fd(0,18);return`<svg viewBox="0 0 25 25" shape-rendering="crispEdges">${o}</svg>`}
const pr=x=>(x.s.length>1?'от ':'')+fm(x.s[0][1]),tg=x=>x.tag?`<span class="tag ${x.tag}">${x.tag==='hit'?'HIT':'NEW'}</span>`:'';
/* pages */
function home(){const nw=ALL.filter(x=>x.tag==='new');return`<div class="pg"><div class="hero"><video src="assets/v1.mp4" poster="assets/v1.jpg" autoplay muted loop playsinline></video><div><div class="hl" id="hl"></div><h1>Кофейня <b>N5</b><br>не просто кофе</h1><p>Авторские напитки, свежая выпечка и десерты. Каждый 6-й напиток — в подарок.</p></div></div>
<a class="gc loy rv" href="#/loyalty">${cup(Math.min(1,S.cups/5))}<div style="flex:1"><h3>Карта лояльности 5+1</h3><p>${S.cups<5?'До подарка осталось '+(5-S.cups):'Следующий напиток бесплатно'}</p><div class="bar"><i style="width:${S.cups/5*100}%"></i></div></div></a>
<h2 class="rv">Акции</h2><div class="feed rv">${PROMOS.map(p=>`<button class="pm" data-p="${p.id}"><img src="assets/${p.img}.jpg" alt="${p.t}"><div><b>${p.t}</b><small>${p.s}</small></div></button>`).join('')}</div>
<h2 class="rv">Главная кофейня</h2><a class="gc rv" href="#/about" style="display:block;text-decoration:none;color:inherit"><div class="row"><span>Адрес</span><b>${MAIN.a}</b></div><div class="row"><span>Режим работы</span><b>${MAIN.h}</b></div><div class="row"><span>Рейтинг</span><b>${MAIN.r} ★ в 2GIS</b></div><div class="btn o" style="margin-top:12px">${ic('pin')}Все локации и режим работы</div></a>
<h2 class="rv">Новинки</h2><div class="feed rv">${nw.map(x=>`<a class="nw" href="#/product/${x.id}"><img src="assets/${x.img}.jpg" alt=""><b>${x.n}</b><small>${pr(x)}</small></a>`).join('')}</div></div>`}
function menu(){const L=mcat==='all'?CATS:CATS.filter(c=>c.id===mcat);return`<div class="pg"><div class="chips">${[{id:'all',n:'Всё'},...CATS].map(c=>`<button class="chip ${c.id===mcat?'on':''}" data-c="${c.id}">${c.n}</button>`).join('')}</div>${L.map(c=>`<h2 class="rv">${c.n}</h2><div class="grid">${c.items.map(x=>`<div class="pc rv"><a class="ph" href="#/product/${x.id}"><img loading="lazy" src="assets/${x.img}.jpg" alt="${x.n}">${tg(x)}</a><div class="in2"><b>${x.n}</b><small>${x.s.map(s=>s[0]).join(' · ')}</small><em>${pr(x)}</em></div><button class="add" data-a="${x.id}">+ Добавить</button></div>`).join('')}</div>`).join('')}<p class="cap" style="margin-top:18px">Если у вас есть аллергия — предупредите кассира.</p></div>`}
function product(id){const x=find(id);if(!x)return'<div class="pg"><p>Позиция не найдена</p></div>';return`<div class="pg pd"><div class="big"><img src="assets/${x.img}.jpg" alt="${x.n}">${tg(x)}</div><h1>${x.n}</h1><p>${x.d||x.cn}</p><div class="lab">${x.s.length>1?'Объём':'Порция'}</div><div class="opt" id="sz">${x.s.map((s,i)=>`<button class="pill ${i?'':'on'}" data-i="${i}">${s[0]} · ${fm(s[1])}</button>`).join('')}</div>
${x.drink?`<div class="lab">Сироп +250 ₸</div><div class="opt" id="sy"><button class="pill on" data-i="-1">Без сиропа</button>${SYR.map((s,i)=>`<button class="pill" data-i="${i}">${s}</button>`).join('')}</div><div class="lab">Молоко</div><div class="opt" id="ml"><button class="pill on" data-i="0">Обычное</button><button class="pill" data-i="1">Альтернативное +690 ₸</button></div>`:''}
<div class="tot"><span>Итого</span><b id="tt"></b></div><button class="btn" id="addp">${ic('cart')}Добавить в корзину</button></div>`}
function bindProduct(id){const x=find(id);if(!x)return;let z=0,y=-1,m=0;const up=()=>$('#tt').textContent=fm(x.s[z][1]+(y>=0?250:0)+(m?690:0));const pick=(q,f)=>{const e=$(q);e&&e.addEventListener('click',ev=>{const b=ev.target.closest('.pill');if(!b)return;e.querySelectorAll('.pill').forEach(p=>p.classList.remove('on'));b.classList.add('on');f(+b.dataset.i);up()})};pick('#sz',i=>z=i);pick('#sy',i=>y=i);pick('#ml',i=>m=i);up();$('#addp').onclick=()=>addCart(id,z,y,m)}
function cart(){if(!C.length)return`<div class="pg"><div class="empty">${ic('cart')}<h3 style="font:700 20px Georgia,serif;color:var(--g)">Корзина пуста</h3><p style="margin:6px 0 18px">Добавьте напитки и выпечку из меню</p><a class="btn" href="#/menu">Перейти в меню</a></div></div>`;
return`<div class="pg"><div class="gc rv">${C.map((l,i)=>{const x=find(l.id);return`<div class="ci"><img src="assets/${x.img}.jpg" alt=""><div><b>${x.n}</b><small>${x.s[l.z][0]}${l.y>=0?' · '+SYR[l.y]:''}${l.m?' · альт. молоко':''}</small><div class="q"><button data-q="${i}" data-d="-1" aria-label="Меньше">−</button><span>${l.q}</span><button data-q="${i}" data-d="1" aria-label="Больше">+</button></div></div><em>${fm(line(l)*l.q)}</em></div>`}).join('')}</div>
<div class="gc rv" style="margin-top:14px"><div class="row"><span>Позиций</span><b>${cnt()}</b></div><div class="tot" style="margin:8px 0 0"><span>Итого</span><b>${fm(sum())}</b></div></div><button class="btn go rv" id="pay" style="margin-top:14px">${ic('lock')}Оформить и оплатить</button><button class="btn o rv" id="clr" style="margin-top:10px">Очистить корзину</button></div>`}
function loyalty(){return`<div class="pg"><div class="gc rv" style="padding:0"><img src="assets/pocket.jpg" alt="" style="width:100%;height:200px;object-fit:cover;display:block"><div style="padding:16px"><h2 style="margin:0 0 6px">Каждый 6-й — бесплатно</h2><p class="cap" style="text-align:left;margin:0">Купите 5 напитков — 6-й в подарок по электронной карте гостя. Напитки копятся бессрочно. В зачёт идут все напитки, кроме литровых чаёв и лимонадов.</p></div></div>
<div class="gc rv" style="margin-top:14px"><div class="cups" id="cups"></div></div>
<div class="gc rv" style="margin-top:14px"><div class="qr" id="qb">${qr(S.id)}<div class="laser"></div></div><p class="cap">Карта ${S.id} · демо-код</p><button class="btn" id="sc">${ic('qr')}[Демо] Сканировать у бариста</button></div></div>`}
function cups(an){$('#cups').innerHTML=[0,1,2,3,4,5].map(i=>`<div>${cup(i<S.cups&&an!==i?1:0)}<small>${i===5?'в подарок':i+1+'-й напиток'}</small></div>`).join('');if(an!=null)setTimeout(()=>{const c=document.querySelectorAll('#cups .cp')[an];c.querySelector('.lv').style.transform='scaleY(1)';c.animate([{transform:'scale(1)'},{transform:'scale(1.18) rotate(-4deg)'},{transform:'scale(1)'}],{duration:900,easing:'ease-out'})},80)}
function bindLoyalty(){cups();tm=setInterval(()=>{const q=$('#qb');q&&(q.firstChild.outerHTML=qr(S.id+Date.now()))},30000);const b=$('#sc');b.onclick=()=>{b.disabled=true;const q=$('#qb');q.classList.add('scan');beep(500,.08);setTimeout(()=>{q.classList.remove('scan');q.classList.add('ok');beep(880,.15);setTimeout(()=>beep(1320,.25),130);navigator.vibrate&&navigator.vibrate([60,40,150]);S.cups++;S.total++;const n=S.cups;S.hist.unshift({t:Date.now(),x:n>=6?'Шестой напиток в подарок':'Напиток №'+n+' зачтён'});cups(n-1);save();setTimeout(()=>{q.classList.remove('ok');b.disabled=false},800);if(n>=6){S.gifts++;setTimeout(()=>{confetti();popup(`<div class="bd">${cup(1)}<h3>Поздравляем!</h3><p>Шестой напиток — в подарок! Новая карта уже ждёт вас: копите следующие 5.</p><button class="btn" onclick="closePop()">Ура!</button></div>`,1);S.cups=0;save();cups()},1700)}},3300)}}
function about(){const ph=['t1','in1','wall','in2','t3','note','t4','latte','choc','tea','honey','berry','brulee','croissant'];return`<div class="pg"><h2 class="rv" style="margin-top:4px">Локации и режим работы</h2>
<div class="gc main rv"><img src="assets/in1.jpg" alt=""><div class="bd2"><h3 style="font:700 20px Georgia,serif;color:var(--g)">Главная кофейня (Центр)</h3><div class="row"><span>Адрес</span><b>${MAIN.a}</b></div><div class="row"><span>Режим работы</span><b>${MAIN.h}</b></div><div class="row"><span>Телефон</span><b><a href="tel:${MAIN.tel}">${MAIN.p}</a></b></div><div class="rt"><b>${MAIN.r}</b><svg viewBox="0 0 24 24">${P.star}</svg><small>${MAIN.aw}</small></div><a class="btn" href="tel:${MAIN.tel}">${ic('phone')}Позвонить</a></div></div>
<h2 class="rv">Другие точки и павильоны</h2>${LOCS.map(l=>`<div class="acc rv"><button>${ic('pin')}${l[0]}${ic('chev').replace('class="i"','class="i ch"')}</button><div class="bd3"><b style="color:var(--g)">${l[1]}</b></div></div>`).join('')}
<h2 class="rv">Видео</h2><div class="vid rv">${[1,2,3,4].map(i=>`<div class="v"><video src="assets/v${i}.mp4" poster="assets/v${i}.jpg" autoplay muted loop playsinline></video><span>${ic('play')}Кофейня N5</span></div>`).join('')}</div>
<h2 class="rv">Фотогалерея</h2><div class="phg">${ph.map(p=>`<img class="rv" loading="lazy" src="assets/${p}.jpg" alt="">`).join('')}</div>
<h2 class="rv">Контакты</h2><div class="gc rv"><div class="row"><span>Instagram</span><b><a target="_blank" rel="noopener" href="https://instagram.com/pekarnya_n5">@pekarnya_n5</a></b></div><div class="row"><span>Бронь столов</span><b>свободная рассадка</b></div><div class="row"><span>С питомцами</span><b>можно, кроме семейного зала</b></div></div></div>`}
function profile(){const t=S.total,st=t>=20?'Знаток N5':t>=6?'Постоянный гость':'Новый гость';return`<div class="pg"><div class="gc pf rv"><div class="av"><img src="assets/logo_kof.png" alt=""></div><div><h3 style="font:700 21px Georgia,serif;color:var(--g)">Гость</h3><div class="bad">${st}</div><p class="cap" style="text-align:left;margin:6px 0 0">Карта ${S.id}</p></div></div><div class="stat rv"><div><b>${t}</b><span>стаканов</span></div><div><b>${S.gifts}</b><span>подарков</span></div><div><b>${5-S.cups}</b><span>до подарка</span></div></div>
<h2 class="rv">История</h2><div class="gc rv">${S.hist.length?S.hist.slice(0,15).map(h=>`<div class="row"><span>${new Date(h.t).toLocaleString('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</span><b>${h.x}</b></div>`).join(''):'<p class="cap" style="margin:0">Пока пусто — отсканируйте карту на странице «5+1».</p>'}</div><button class="btn o rv" id="rs" style="margin-top:14px">Сбросить демо-данные</button></div>`}
/* fx */
function popup(h,mid){const p=$('#pop');p.className='on'+(mid?' mid':'');p.innerHTML=`<div class="sh">${h}</div>`}function closePop(){$('#pop').className=''}
$('#pop').addEventListener('click',e=>{if(e.target.id==='pop')closePop()});
function beep(f,d){try{const a=window._a||(window._a=new(window.AudioContext||window.webkitAudioContext)()),o=a.createOscillator(),g=a.createGain();o.type='triangle';o.frequency.value=f;g.gain.setValueAtTime(.2,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d+.1);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+d+.12)}catch(e){}}
function confetti(){const c=$('#cf'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const col=['#0f4c3a','#c9a24b','#2d7a5c','#e6c77a','#f3ead7'],Pn=[];for(let k=0;k<4;k++)for(let i=0;i<60;i++){const a=-Math.PI/2+(Math.random()-.5)*1.4,v=8+Math.random()*10;Pn.push({x:innerWidth*(.2+k*.2),y:innerHeight*.7,vx:Math.cos(a)*v,vy:Math.sin(a)*v,c:col[i%5],s:3+Math.random()*5,d:k*14})}let f=0;(function d(){x.clearRect(0,0,c.width,c.height);Pn.forEach(p=>{if(f<p.d)return;p.x+=p.vx;p.y+=p.vy;p.vy+=.3;p.vx*=.99;x.fillStyle=p.c;x.fillRect(p.x,p.y,p.s,p.s*1.7)});if(++f<200)requestAnimationFrame(d);else x.clearRect(0,0,c.width,c.height)})()}
function promo(id){const p=PROMOS.find(a=>a.id===id);popup(`<img class="cv" src="assets/${p.img}.jpg" alt=""><div class="bd"><h3>${p.t}</h3><p>${p.d}</p><button class="btn" id="pa">${p.b}</button><button class="btn o" onclick="closePop()">Закрыть</button></div>`);$('#pa').onclick=()=>{closePop();location.hash='#'+p.to}}
/* router */
const order=['home','menu','loyalty','cart','about','profile'];
function route(){clearInterval(tm);closePop();const h=location.hash.slice(1)||'/home',parts=h.split('/'),key=parts[1]||'home',m=key==='product';if(key==='menu'&&parts[2]&&CATS.some(c=>c.id===parts[2]))mcat=parts[2];
const tab=m?'menu':(order.includes(key)?key:'home'),prev=hist[hist.length-2],bw=prev===h||(!m&&cur!=='product'&&order.indexOf(tab)<order.indexOf(cur));if(prev===h)hist.pop();else if(hist[hist.length-1]!==h)hist.push(h);
document.body.classList.toggle('bw',bw);document.body.classList.toggle('fw',!bw);
V.innerHTML=m?product(parts[2]):({menu,loyalty,cart,about,profile}[tab]||home)();window.scrollTo(0,0);cur=m?'product':tab;
$('#hd').classList.toggle('sub',m||tab!=='home');$('#ht').innerHTML=tab==='home'?'<span>Кофейня N5</span>':({menu:'Меню',loyalty:'Карта 5+1',cart:'Корзина',about:'Кофейня',profile:'Профиль'}[tab]||'');
$('#hc').innerHTML=ic('phone');$('#bk').innerHTML=ic('back');
$('#nav').innerHTML=NAV.map(n=>`<a href="#/${n[0]}" class="${n[0]===tab?'on':''}">${ic(n[0])}${n[1]}${n[0]==='cart'?'<span class="bdg" id="bdg"></span>':''}</a>`).join('');badge();
const hl=$('#hl');if(hl){hl.innerHTML=logo();const s=hl.firstChild;fitLogo(s);s.classList.add('done')}
if(m)bindProduct(parts[2]);if(tab==='loyalty')bindLoyalty();
V.querySelectorAll('.pm').forEach(b=>b.onclick=()=>promo(b.dataset.p));
V.querySelectorAll('.acc button').forEach(b=>b.onclick=()=>b.parentNode.classList.toggle('open'));
if(tab==='menu'&&!m){V.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{mcat=b.dataset.c;const t=scrollY;route();scrollTo(0,t)});V.querySelectorAll('.add').forEach(b=>b.onclick=()=>{addCart(b.dataset.a);b.classList.add('ok');b.textContent='Добавлено';setTimeout(()=>{b.classList.remove('ok');b.textContent='+ Добавить'},1100)})}
if(tab==='cart'&&C.length){V.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{const l=C[+b.dataset.q];l.q+=+b.dataset.d;if(l.q<1)C.splice(+b.dataset.q,1);save();const y=scrollY;route();scrollTo(0,y)});$('#clr').onclick=()=>{C=[];save();route()};$('#pay').onclick=()=>popup(`<div class="bd"><div class="ic">${ic('lock')}</div><h3>Демо-режим</h3><p>Оплата будет доступна в официальном мобильном приложении iOS / Android</p><button class="btn" onclick="closePop()">Понятно</button></div>`,1)}
if(tab==='profile')$('#rs').onclick=()=>{S={cups:0,total:0,gifts:0,hist:[],id:S.id};save();route()};
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.06});V.querySelectorAll('.rv').forEach((e,i)=>{e.style.transitionDelay=Math.min(i%6,5)*60+'ms';io.observe(e)})}
$('#bk').onclick=()=>hist.length>1?history.back():(location.hash='#/home');addEventListener('hashchange',route);
/* splash */
(function(){const a=$('#sl');a.innerHTML=logo();const M=[[0,'Загружаем меню и атмосферу...'],[30,'Обжариваем зёрна...'],[60,'Печём свежие круассаны...'],[88,'Почти готово...']];
const go=()=>{burn(a.firstChild,2800);let p=0;const t=setInterval(()=>{p=Math.min(100,p+.9+Math.random()*1.4);$('#pf').style.width=p+'%';$('#pp').textContent=Math.floor(p)+'%';$('#pt').textContent=M.filter(m=>p>=m[0]).pop()[1];if(p>=100){clearInterval(t);setTimeout(()=>{$('#splash').classList.add('out');document.body.classList.remove('lock');$('#sv').pause()},1500)}},50)};
const im=new Image();im.onload=im.onerror=go;im.src='assets/logo_kof.png';route()})();
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
